#/api/v1/dd-systems/{SYSTEM-ID}/file-systems/block-storages
- name: Set Operation {{ operation }}
  set_fact: 
    body: 
      operation: "{{ operation }}"
      timezone:  "{{ timezone }}"
  when: operation == "set_timezone"
- name: Set DD NTP {{ operation }}
  vars:
    operations:
      - set_timezone
  uri:
    method: PUT
    url: "{{ ppdd_baseurl }}:{{ ppdd_port }}/{{ ppdd_api_ver }}/dd-systems/{{ system_id }}/settings"
    body_format: json
    body: "{{ body }}"
    headers:
      X-DD-AUTH-TOKEN: "{{ access_token }}"    
    status_code: 200,500, -1
    validate_certs: false
  register: result  
  when: not ansible_check_mode and operation in operations
- set_fact:
    settings: "{{ result.json if result.json is defined}}"
- debug:
    msg:  "{{ settings if settings is defined }}"
    verbosity: 1


