#/ /api/v3/dd-systems/{SYSTEM-ID}/networks/dns-servers
- name: Set Network Physical Interface
  uri:
    url: "{{ ppdd_baseurl }}:{{ ppdd_port }}/{{ ppdd_api_ver }}/dd-systems/{{ system_id }}/networks/interfaces/physicals/{{ interface }}"
    method: PUT
    body_format: json
    body:
      address: "{{ address }}"
      netmask: "{{ netmask }}"
      dhcp: "{{ dhcp }}"
    headers:
      X-DD-AUTH-TOKEN: "{{ access_token }}"    
    status_code: "{{ status_code }}"
    validate_certs: false
  register: result  
  when: not ansible_check_mode 
- set_fact:
    networks: "{{ result.json }}"
  when: result.json is defined and not ansible_check_mode
