# Example Playbok to configure PPDD
- name: Configure PowerProtect DataDomain Appliance initial Password
  hosts: localhost
  connection: local
  vars_files: 
    - ./vars/main.yml
  tasks:
  - name: Checking if PPDD FQDN / IP is set
    fail: 
      msg: "We do not have ppdd fqdn set !"
    when: (ppdd_fqdn is not defined) or (ppdd_fqdn|length <= 8)
  - name: Checking ppdd_username is set
    fail: 
      msg: "We do not have ppdd_username set! Check vars/main.yml for assignment from env vars"
    when: (ppdd_username is not defined) or (ppdd_username|length == 0)      
  - name: Checking PPDD_PASSWORD is set
    fail: 
      msg: "We do not have ppdd_password  set ! Check vars/main.yml for assignment from env vars"
    when: (ppdd_password is not defined) or (ppdd_password|length == 0)  
  - name: Checking PPDD_INITIAL_PASSWORD
    fail: 
      msg: "We do not have ppdd_initial_password  set ! Check vars/main.yml for assignment from env vars"
    when: (ppdd_initial_password is not defined) or (ppdd_initial_password|length == 0)                           
  - name: Setting Base URL
    set_fact: 
      ppdd_baseurl: "{{ ppdd_fqdn }}"  
  - name: Check DataDomain Appliance Ready {{ ppdd_fqdn }}
    include_role:
      name: wait_ppdd_api_ready 
  - debug: 
      msg: "{{ result }}"
      verbosity: 1            
  - name: Get PPDD Token for {{ ppdd_fqdn }}
    vars:
      status_code: 201,500 #,401
      username: "{{ ppdd_username }}"
      password: "{{ ppdd_initial_password }}"
      retries: 5
      delay: 60
    include_role: 
      name: get_ppdd_token
  - name: Fail NO ACCESS TOKEN
    fail:
      msg: failed
    when: access_token is not defined    
  - name: Set PPDD User Password for sysadmin at {{ ppdd_fqdn }}
    vars:
      user: "{{ ppdd_username }}"
      current_password: "{{ ppdd_initial_password }}"
      new_password: "{{ ppdd_password }}"
      status_code: 200
    include_role: 
      name: set_ppdd_user_password 
    when: access_token is defined  
 
