# Example Playbok to configure PPDD
- name: Check PowerProtect DataDomain ATOS ( Active Tier on Object) for Azure
  hosts: localhost
  connection: local
  vars_files: 
    - ./vars/main.yml
  tasks:
  - name: Checking if PPDD FQDN / IP is set
    fail: 
      msg: "We do not have ppdd fqdn set !"
    when: (ppdd_fqdn is not defined) or (ppdd_fqdn|length <= 8)
  - name: Checking PPDD_PASSWORD is set
    fail: 
      msg: "We do not have ppdd_password  set !"
    when: (ppdd_password is not defined) or (ppdd_password|length == 0)
  - name: Checking if atos_container is set
    fail: 
      msg: "We do not have atos_container set !"
    when: (atos_bucket is not defined) or (atos_container|length <= 5)    
  - name: Checking if atos_storageaccount is set
    fail: 
      msg: "We do not have atos_storageaccount set !"
    when: (atos_bucket is not defined) or (atos_storageaccount|length <= 8)        
  - name: Setting Base URL
    set_fact: 
      ppdd_baseurl: "{{ ppdd_fqdn }}"  
  - name: Check DataDomain Appliance Ready {{ ppdd_fqdn }}
    include_role:
      name: wait_ppdd_api_ready 
  - debug: 
      msg: "{{ result }}"
      verbosity: 1            
  - name: Get PPDD Token for {{ ppdd_fqdn }}
    vars:
      username: "{{ ppdd_username }}"
      password: "{{ ppdd_password }}"
    include_role: 
      name: get_ppdd_token
  - debug: 
      msg: "{{ access_token }}"
      verbosity: 1


  - name: Get Active Tier on Object Status
    include_role: 
      name: get_ppdd_file-systems_object-stores  

  - name: Enable DDBoost
    include_role: 
      name: set_ppdd_boostService
    vars:
      operation: "enable" 