# Example Playbok to configure PPDD
- name: Playbook to configure DataDomain for PPDM
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files: 
    - ../vars/main.yml  
  tasks:
  - name: Checking if PPDD FQDN / IP is set
    fail: 
      msg: "We do not have ppdd fqdn set !"
    when: (ppdd_fqdn is not defined) or (ppdd_fqdn|length <= 8)
  - name: Checking PPDD_PASSWORD is set
    fail: 
      msg: "We do not have ppdd_password  set !"
    when: (ppdd_password is not defined) or (ppdd_password|length == 0)  
  - name: Setting Base URL
    set_fact: 
      ppdd_baseurl: "{{ ppdd_fqdn }}"  
  - name: Get PPDD Token for {{ ppdd_fqdn }}
    vars: 
      username: "{{ ppdd_username }}"
      password: "{{ ppdd_password }}"
  
    include_role: 
      name: ../roles/get_ppdd_token
  - debug: 
      msg: "{{ access_token }}"
      verbosity: 1

  - name: Get Appliance Disks {{ ppdd_fqdn }}
    include_role: 
      name: ../roles/get_ppdd_disks
    vars:
      filter: "status=UNKNOWN and tierType=OTHER and capacity=(536870912000,1536870912000)"
  - debug:
      msg: "{{ disks  }}"
      verbosity: 0      
  - name: Display FIltered Results
    vars:
      query: >-
          diskInfo[].device
    debug:
      msg: "{{ disks | community.general.json_query(query) }}"
      verbosity: 0 
 