# Example Playbok to configure PPDD
- name: Configure PPDD
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files: 
    - ./vars/main.yml
  tasks:
  - name: Checking Required Variables
    fail: 
      msg: "We do not have ppdd fqdn set !"
    when: (ppdd_fqdn is not defined) or (ppdd_fqdn|length <= 8)
  - name: Checking Required Variables
    fail: 
      msg: "We do not have ppdd_password  set !"
    when: (ppdd_password is not defined) or (ppdd_password|length == 0)      
  - name: Setting Base URL
    set_fact: 
      ppdd_baseurl: "{{ ppdd_fqdn }}"  
  - name: Get PPDD Token for {{ ppdd_fqdn }}
    include_role: 
      name: get_ppdd_token
  - debug: 
      msg: "{{ access_token }}"
      verbosity: 1
  - name: Get PPDD file-systems {{ ppdd_fqdn }}
    include_role: 
      name: get_ppdd_protocols-ddboost_clients
  - debug: 
      msg: "{{ protocol_ddboost_clients }}"
      verbosity: 0           



