# Example Playbok to configure PPDD
- name: Get PowerProtect dDataDomain Network Configuration
  hosts: localhost
  connection: local
  vars_files: 
    - ../vars/main.yml
  tasks:
  - name: Checking Required Variables
    fail: 
      msg: "We do not have ppdd fqdn set !"
    when: (ppdd_fqdn is not defined) or (ppdd_fqdn|length <= 8)
  - name: Checking Required Variables
    fail: 
      msg: "We do not have ppdd_password  set !"
    when: (ppdd_password is not defined) or (ppdd_password|length == 0)      
  - name: Setting Base URL
    set_fact: 
      ppdd_baseurl: "{{ ppdd_fqdn }}"  
  - name: Get PPDD Token for {{ ppdd_fqdn }}
    include_role: 
      name: ../roles/get_ppdd_token
    vars:
      password: "{{ ppdd_password }}"  
  - debug: 
      msg: "{{ access_token }}"
      verbosity: 1
  - name: Get PPDD networks {{ ppdd_fqdn }}
    vars:
      network_id: ""
      
    include_role: 
      name: ../roles/get_ppdd_networks
  - debug: 
      msg: "{{ networks }}"
      verbosity: 0           



