# Example Playbok to configure PPDD
- name: Configure PPDD
  hosts: localhost
  connection: local
  vars_files: 
    - ./vars/main.yml
  tasks:
  - name: Checking Required Variables
    fail: 
      msg: "We do not have ppdd fqdn set !"
    when: (ppdd_fqdn is not defined) or (ppdd_fqdn|length <= 8)
  - name: Checking PPDD_PASSWORD
    fail: 
      msg: "We do not have ppdd_password  set !"
    when: (ppdd_password is not defined) or (ppdd_password|length == 0) 
  - name: Checking PPDD_NEW_PASSWORD
    fail: 
      msg: "We do not have ppdd_new_password  set !"
    when: (ppdd_new_password is not defined) or (ppdd_new_password|length == 0)             
  - name: Setting Base URL
    set_fact: 
      ppdd_baseurl: "{{ ppdd_fqdn }}"  
  - name: Get PPDD Token for {{ ppdd_fqdn }}
    include_role: 
      name: get_ppdd_token
  - debug: 
      msg: "{{ access_token }}"
      verbosity: 1
  - name: Set PPDD User Password for sysadmin at {{ ppdd_fqdn }}
    vars:
      user: "{{ ppdd_username }}"
      current_password: "{{ ppdd_password }}"
      new_password: "{{ ppdd_new_password }}"
    include_role: 
      name: set_ppdd_user_password
  - debug: 
      msg: "{{ users }}"
      verbosity: 0           



