#/api/v1/dd-systems/{SYSTEM-ID}/file-systems/block-storages
- name: Checking Mtree already exists
  include_role: 
    name: get_ppdd_mtrees
  vars:
    id: "/data/col1/{{ mtree_name | basename }}"    
- debug:
   msg: "mtree {{ mtree_name }} already defined"

- name: New DD Mtree {{ mtree_name }}
  uri:
    method: POST
    url: "{{ ppdd_baseurl }}:{{ ppdd_port }}/{{ ppdd_api_ver }}/dd-systems/{{ system_id }}/mtrees"
    body_format: json
    body: |
        {
          "name": "/data/col1/{{ mtree_name | basename }}"
        }
    headers:
      X-DD-AUTH-TOKEN: "{{ access_token }}"    
    status_code: 201,400, -1
    validate_certs: false
  register: result  
  when: not ansible_check_mode and mtrees is not defined
- set_fact:
    mtree: "{{ result.json }}"
  when: result.json is defined
- set_fact:
    mtree: "{{ mtrees }}"
  when: mtrees is defined
- debug:
    msg:  "{{ mtree }}"
    verbosity: 1




