#/api/v1/dd-systems/{SYSTEM-ID}/file-systems/block-storages
- name: New DD Mtree {{ mtree_name }}
  uri:
    method: POST
    url: "{{ ppdd_baseurl }}:{{ ppdd_port }}/{{ ppdd_api_ver }}/dd-systems/{{ system_id }}/mtrees"
    body_format: json
    body: |
        {
          "name": "{{ mtree_name }}"
        }
    headers:
      X-DD-AUTH-TOKEN: "{{ access_token }}"    
    status_code: 201,400, -1
    validate_certs: false
  register: result  
  when: not ansible_check_mode
- set_fact:
    mtree: "{{ result.json if result.json is defined}}"
- debug:
    msg:  "{{ mtree if mtree is defined }}"
    verbosity: 0


