#/rest/v1.0/dd-systems/{SYSTEM-ID}/snapshots
- name: Define uri with id
  set_fact: 
    uri: "{{ ppdd_baseurl }}:{{ ppdd_port }}/{{ ppdd_api_ver }}/dd-systems/{{ system_id }}/snapshots/{{ snapshot_id }}"
  when: snapshot_id  | default('', true) | trim != ''
- name: Define uri without id
  set_fact: 
    uri: "{{ ppdd_baseurl }}:{{ ppdd_port }}/{{ ppdd_api_ver }}/dd-systems/{{ system_id }}/snapshots"
  when: snapshot_id  | default('', false) | trim == ''
- name: Get PPDD Snapshots
  uri:
    method: GET
    url: "{{ uri }}"
    body_format: form-urlencoded
    body:
    headers:
      X-DD-AUTH-TOKEN: "{{ access_token }}"    
    status_code: 200
    validate_certs: false
  register: result  
  when: not ansible_check_mode 
- set_fact:
    snapshots: "{{ result.json }}"
