#/api/v1/dd-systems/{SYSTEM-ID}/file-systems/block-storages
- name: Set DD Filesystems {{ operation }}
  vars:
    operations:
      - enable
      - disable
      - clean_start
      - create
      - destroy
  uri:
    method: PUT
    url: "{{ ppdd_baseurl }}:{{ ppdd_port }}/{{ ppdd_api_ver }}/dd-systems/{{ system_id }}/file-systems"
    body_format: json
    body:
      operation: "{{ operation }}"
    headers:
      X-DD-AUTH-TOKEN: "{{ access_token }}"    
    status_code: 200,500, -1
    timeout: 600
    validate_certs: false
  register: result  
  when: not ansible_check_mode and operation in operations
- set_fact:
    file_systems_block_storages: "{{ result.json if result.json is defined}}"
- debug:
    msg:  "{{ file_systems_block_storages if file_systems_block_storages is defined }}"
    verbosity: 1
  


