#/api/v1/dd-systems/{SYSTEM-ID}/file-systems/block-storages
- name: Set DD Boost {{ operation }}
  vars:
    operations:
      - enable
      - disable
  uri:
    method: PUT
    url: "{{ ppdd_baseurl }}:{{ ppdd_port }}/{{ ppdd_api_ver }}/dd-systems/{{ system_id }}/protocols/ddboost"
    body_format: json
    body: |
        {
          "operation": "{{ operation }}"
        }
    headers:
      X-DD-AUTH-TOKEN: "{{ access_token }}"    
    status_code: 200,500, -1
    validate_certs: false
  register: result  
  when: not ansible_check_mode and operation in operations
- set_fact:
    ddboost: "{{ result.json if result.json is defined}}"
- debug:
    msg:  "{{ ddboost if ddboost is defined }}"
    verbosity: 0
#  when: file_systems_block_storages is defined  


