#/api/v2/dd-systems/{SYSTEM-ID}/data-movement
- name: Get PPDD data-movement
  uri:
    method: GET
    url: "{{ ppdd_baseurl }}:{{ ppdd_port }}/{{ ppdd_api_ver }}/dd-systems/{{ system_id }}/data-movement"
    body_format: form-urlencoded
    body:
      exclude_fields: status
    headers:
      X-DD-AUTH-TOKEN: "{{ access_token }}"    
    status_code: 200
    validate_certs: false
  register: result  
  when: not ansible_check_mode 
- set_fact:
    data_movement: "{{ result.json }}"
